<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="Waitlist_Transparency_System.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <h3>HOW IT WORKS</h3>
<p class="bodytext">Child care facilities which are properly licensed update their wait list information through WaitlistTransparency.com. When families visit the website to search for child care and provide their desired location and child’s birth date, the system queries the lists and returns an expected enrollment date based on the likely transition date of children currently enrolled in the program. This date is meant to give you a tentative timeline only. Wait list statuses change frequently based on more than age alone. For instance, families might move and un-enroll their child from a facility which will create a spot in the program sooner than anticipated. Likewise, the timeline could increase if the program has a prioritized wait list and families with a high priority status enroll (i.e. a sibling priority). It is best you use your search results for setting expectations. </p>
    <h3>OUR MISSION</h3>
<p class="bodytext">Caring for a child is a big task. This is the understatement of the century. As a parent myself I know it is important to find quality child care or else you are unable to be the best you can be in your other endeavors. The idea for this site came about after my family and I considered relocating to a new city. I went through the process of contacting individual child care facilities that came up in my internet search results. On top of many other questions, I asked when I might be able to enroll my child in the program. I received discouraging responses. “It will be around 12-months plus.” Given the quick response every time, I could tell it was a standard reply. All I really knew is they had no immediate space available, but other than that I could not properly plan a move on any tentative timeline. On top of the generic responses, I had a difficult time learning where all the licensed 
    facilities were even located. Needless to say, the process left me unsatisfied. A light bulb went off. If this tool helps one person in their journey to securing quality care, my job is done. I hope it helps a lot more than that though. My goal is to ensure everyone is equipped to make educated decisions about where to place their child. I hope it drives business to facilities who can provide the best care possible and reduces the risk of children being put in situations where their safety or development is at risk. Lastly, I hope this allows families to maintain privacy as they seek care for their children. No matter what the circumstance, this tool is only meant to help connect families with quality child care providers. Happy connecting, </p>
    <p>Kyndall Carey</p>
</asp:Content>
